server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://123.56.4.32/security_study
    password: Pass@word01!
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  data:
    redis:
      host: 123.56.4.32
      jedis:
        pool:
          max-wait: -1
          max-active: 8
          min-idle: 8
      port: 6379
      password: daozitutu
      database: 0




